language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -r dev-requirements.txt

script:
  - py.test -v .
  - pytest --cov=./
  - codecov

notifications:
  slack: urduhack:HarNbK5WrXQbu9XuFLPsSFtM
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch:
      - master
      - /?(\d+\.)?(\d+\.)?(\*|\d+)$/
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
